name: one_data_taxi_app_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^5.4.1
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^1.0.0+1

  #hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  path: ^1.9.0

  #di
  get_it: ^8.0.0

  #state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.5
  rxdart: ^0.27.7

  #map
  yandex_mapkit: ^4.1.0
  location: ^7.0.0
  geolocator: ^12.0.0

  #system
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.8
  intl: ^0.19.0

  #ui
  cached_network_image: any
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_local_notifications: ^17.2.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
          style: italic
